### register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "teste@exemplo.com",
    "password": "senha123",
    "fullname": "teste"
}

### login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "teste@exemplo.com",
    "password": "senha123"
}

### refresh token
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RlQGV4ZW1wbG8uY29tIiwic3ViIjoiNDcyMjkwNjEwNTg1NjAiLCJpYXQiOjE3Mjg1ODAzOTAsImV4cCI6MTcyODU4Mzk5MH0.8RPYQxP7y8pCyoBMrV6qGoeQs0xtLLTgu3BA0YdRVDs"
}

### confirm email
GET http://localhost:3000/auth/confirm-email?token=760afc71-819b-45a9-9b47-eafde0e9b9a5