### register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "teste@exemplo.com",
    "password": "senha123",
    "fullname": "teste"
}

### login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "teste@exemplo.com",
    "password": "senha125"
}

### confirm email
GET http://localhost:3000/auth/confirm-email?token=760afc71-819b-45a9-9b47-eafde0e9b9a5